[package]
name = "DU_analog_inputs"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.8.2"
serde = "0.9.15"
config = "0.13.1"
enigo = "0.0.14"
spin_sleep = "0.3.7"
keyboard_query = "0.1.0"