device_pollrate = "250" #This is the pollrate per second to check on device state.
input_sendrate_division = "6" #This value tells how many polls to wait before sending an input to mouse.
debug = true #This value prints debug information to the console to enumerate all input codes.
sixaxis = true #This value toggles between sixaxis and 5axis encoding. Sixaxis is used when true