on:
  push:
    branches: [master]

jobs:
  build:
    name: Rust The Ruilder
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git vcp
          vcp\bootstrap-vcpkg.bat
      - name: Set env
        shell: bash
        run: |
          echo "VCPKG_ROOT=${{ github.workspace }}\vcp" >> $GITHUB_ENV
      - name: Compile
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-vcpkg
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Github Rusty Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.0.3
          release_name: v2.0.3 More
          draft: true
          prerelease: false
      - name: Upload release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target\release\DU_analog_inputs.exe
          asset_name: DU_Analog_Inputs_v203.exe
          asset_content_type: application/zip
      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}